module.exports = {
    BEFORE: -1,
    WELCOME: 0,
    DELETE_CHARACTER: 1,
    NAME:2,
    CONCEPT:3,
    CLAN:4,

    ATTRIBUTE_4:5, // 1 attribute at 4
    ATTRIBUTE_3:6, // 3 attributes at 3
    ATTRIBUTE_2:7,  // 4 attributes at 2

    SKILL_DISTRIBUTION:8,

    JACK_3: 9, // 1 skill at 3
    JACK_2: 10, // 8 skills at 2
    JACK_1: 11, // 10 skills at 1

    BALANCED_3:12, // 3 skills at 3
    BALANCED_2:13, // 5 skills at 2
    BALANCED_1:14, // 7 skills at 1

    SPECIALIST_4:15, // 1 skill at 4
    SPECIALIST_3:16, // 3 skills at 3
    SPECIALIST_2:17, // 3 skills at 2
    SPECIALIST_1:18, // 3 skills at 1

    SPECIALITY_ACADEMICS:19,
    SPECIALITY_CRAFT:20,
    SPECIALITY_PERFORMANCE:21,
    SPECIALITY_SCIENCE:22,
    SPECIALITY:23,
    
    DISCIPLINES_2:24,
    POWER_1:25,
    POWER_2:26,
    DISCIPLINES_1:27,
    POWER_3:28,

    PREDATOR:29,
    PREDATOR_CHARACTERISTIC_1:30,
    PREDATOR_CHARACTERISTIC_2:31,
    PREDATOR_CHARACTERISTIC_3:32,
    PREDATOR_CHARACTERISTIC_4:33,
    PREDATOR_CHARACTERISTIC_5:34,
    PREDATOR_CHARACTERISTIC_6:35,

    ADVANTAGES_MERIT:36,
    ADVANTAGES_MERIT_CONFIRM_UNSPENT:37,
    ADVANTAGES_FLAWS:38,
    ADVANTAGES_FLAWS_CONFIRM_OVERSPENT:39,

    THIN_BLOOD_MERITS:40,
    THIN_BLOOD_FLAWS:41,

    CONVICTIONS_TOUCHSTONES:42,
    
    FINISH:99,
}
