module.exports = {
    'athletics':['ath'],
    'brawl':['bra'],
    'craft':['cra'],
    'drive':['dri'],
    'firearms':['fir'],
    'melee':['mel'],
    'larceny':['lar'],
    'stealth':['ste'],
    'survival':['sur'],
    'animal_ken':['ani', 'animal'],
    'etiquette':['eti'],
    'insight':['ins'],
    'intimidation':['inti'],
    'leadership':['lea', 'lead'],
    'performance':['perf'],
    'persuasion':['pers'],
    'streetwise':['stre', 'street'],
    'subterfuge':['sub'],
    'academics':['aca'],
    'awareness':['awa'],
    'finance':['fin'],
    'investigation':['inv'],
    'medicine':['med'],
    'occult':['occ'],
    'politics':['pol'],
    'science':['sci'],
    'technology':['tec', 'tech']
}
